# Generated by Django 5.0.6 on 2024-06-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('problem_title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
